{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uber",
    "module": "authService",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "authService-0.0.1-SNAPSHOT-plain.jar",
          "url": "authService-0.0.1-SNAPSHOT-plain.jar",
          "size": 33138,
          "sha512": "97e81838ebf5a49dde2f65829c931bcf3c770d30cc86780e3fb5217ca2e434398f410a6b283c9b8e4a6a68c7a4bc154dcbe995aa82655d19be4eb46da7585f00",
          "sha256": "490ba4da1b57b4393ba7237cee80f899f8096fdebe05512f76a937843d5349e6",
          "sha1": "5ea85eaaec003b6832d8b90d779d541fdb142acd",
          "md5": "93b12e86809e8412ec5514cdbf7ff0fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-oauth2-client"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.3"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.3"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "authService-0.0.1-SNAPSHOT-plain.jar",
          "url": "authService-0.0.1-SNAPSHOT-plain.jar",
          "size": 33138,
          "sha512": "97e81838ebf5a49dde2f65829c931bcf3c770d30cc86780e3fb5217ca2e434398f410a6b283c9b8e4a6a68c7a4bc154dcbe995aa82655d19be4eb46da7585f00",
          "sha256": "490ba4da1b57b4393ba7237cee80f899f8096fdebe05512f76a937843d5349e6",
          "sha1": "5ea85eaaec003b6832d8b90d779d541fdb142acd",
          "md5": "93b12e86809e8412ec5514cdbf7ff0fd"
        }
      ]
    }
  ]
}
